[package]
name = "audiowaveform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Audio waveform generation, serialization, rendering, and transcoding library"

[[example]]
name = "generate_waveform"
required-features = ["decode"]

[[example]]
name = "render_waveform"
required-features = ["render"]

[[example]]
name = "generate_from_pcm"

[[example]]
name = "resample_waveform"

[[test]]
name = "generate"
required-features = ["decode"]

[[test]]
name = "render"
required-features = ["render"]

[[test]]
name = "wav"
required-features = ["wav"]

[features]
default = ["decode", "render", "wav"]
decode = ["dep:symphonia"]
render = ["dep:image", "dep:png"]
wav = ["dep:hound"]

[dependencies]
byteorder.workspace = true
hound = { workspace = true, optional = true }
image = { workspace = true, optional = true }
png = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
symphonia = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
image.workspace = true
predicates.workspace = true
tempfile.workspace = true
