name: Rust

on: [push]

jobs:
  library-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            command: cargo test -p audiowaveform
          - name: no-default-features
            command: cargo test -p audiowaveform --no-default-features
          - name: decode
            command: cargo test -p audiowaveform --no-default-features --features decode
          - name: render
            command: cargo test -p audiowaveform --no-default-features --features render
          - name: wav
            command: cargo test -p audiowaveform --no-default-features --features wav

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test CLI
        run: cargo test -p audiowaveform-cli
